import * as constants from '../../secret.js';

export const FIREBASE_API_KEY = constants.SECRET_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = constants.SECRET_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_DATABASE_URL = constants.SECRET_FIREBASE_DATABASE_URL;
export const FIREBASE_PROJECT_ID = constants.SECRET_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = constants.SECRET_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = constants.SECRET_FIREBASE_MESSAGING_SENDER_ID;

export const FACEBOOK_APP_ID = constants.SECRET_FACEBOOK_APP_ID;
